apiVersion: apps/v1
kind: Deployment
metadata:
  name: zammad-redis
  namespace: zammad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zammad-redis
  template:
    metadata:
      labels:
        app: zammad-redis
    spec:
      containers:
        - name: zammad-redis
          image: redis:7.4.3-alpine
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: zammad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
