apiVersion: apps/v1
kind: Deployment
metadata:
  name: zammad-postgresql
  namespace: zammad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zammad-postgresql
  template:
    metadata:
      labels:
        app: zammad-postgresql
    spec:
      containers:
        - name: zammad-postgresql
          image: postgres:17.5-alpine
          env:
            - name: POSTGRES_DB
              value: zammad_production
            - name: POSTGRES_USER
              value: zammad
            - name: POSTGRES_PASSWORD
              value: zammad
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: zammad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
