apiVersion: v1
kind: Service
metadata:
  name: zammad-postgresql
  namespace: zammad
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: zammad-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: zammad-redis
  namespace: zammad
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: zammad-redis
---
apiVersion: v1
kind: Service
metadata:
  name: zammad-elasticsearch
  namespace: zammad
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: zammad-elasticsearch
