apiVersion: apps/v1
kind: Deployment
metadata:
  name: zammad-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zammad-elasticsearch
  template:
    metadata:
      labels:
        app: zammad-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: bitnami/elasticsearch:8.18.0
          env:
            - name: ELASTICSEARCH_ENABLE_SECURITY
              value: 'true'
            - name: ELASTICSEARCH_SKIP_TRANSPORT_TLS
              value: 'true'
            - name: ELASTICSEARCH_ENABLE_REST_TLS
              value: 'false'
            - name: ELASTICSEARCH_PASSWORD
              value: zammad
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /bitnami/elasticsearch/data
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zammad-elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: zammad-elasticsearch