apiVersion: apps/v1
kind: Deployment
metadata:
  name: zammad-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zammad-memcached
  template:
    metadata:
      labels:
        app: zammad-memcached
    spec:
      containers:
        - name: memcached
          image: memcached:1.6.38-alpine
          args: ["memcached", "-m", "256M"]
          ports:
            - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: zammad-memcached
spec:
  ports:
    - port: 11211
      targetPort: 11211
  selector:
    app: zammad-memcached