apiVersion: apps/v1
kind: Deployment
metadata:
  name: zammad-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zammad-postgresql
  template:
    metadata:
      labels:
        app: zammad-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:17.5-alpine
          env:
            - name: POSTGRES_DB
              value: zammad_production
            - name: POSTGRES_USER
              value: zammad
            - name: POSTGRES_PASSWORD
              value: zammad
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zammad-postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: zammad-postgresql