apiVersion: v1
kind: ConfigMap
metadata:
  name: zammad-config
data:
  POSTGRESQL_DB: zammad_production
  POSTGRESQL_HOST: zammad-postgresql
  POSTGRESQL_USER: zammad
  POSTGRESQL_PASS: zammad
  POSTGRESQL_PORT: "5432"
  REDIS_URL: redis://zammad-redis:6379
  ELASTICSEARCH_SCHEMA: http
  ELASTICSEARCH_HOST: zammad-elasticsearch
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_USER: elastic
  ELASTICSEARCH_PASS: zammad
  ELASTICSEARCH_NAMESPACE: zammad
  ELASTICSEARCH_REINDEX: "true"
  BACKUP_DIR: "/var/tmp/zammad"
  BACKUP_TIME: "03:00"
  HOLD_DAYS: "10"
  TZ: "Europe/Berlin"
  NGINX_PORT: "8080"
  NGINX_CLIENT_MAX_BODY_SIZE: "50M"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zammad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zammad
  template:
    metadata:
      labels:
        app: zammad
    spec:
      containers:
        - name: zammad
          image: ghcr.io/zammad/zammad:6.5.0-75
          envFrom:
            - configMapRef:
                name: zammad-config
          ports:
            - containerPort: 3000  # Rails
            - containerPort: 8080  # Nginx
          volumeMounts:
            - name: zammad-storage
              mountPath: /opt/zammad/storage
      volumes:
        - name: zammad-storage
          persistentVolumeClaim:
            claimName: zammad-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zammad
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
    - port: 3000
      targetPort: 3000
  selector:
    app: zammad