apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o K8S-compose/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: zammad-postgresql
  name: zammad-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zammad-postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o K8S-compose/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: zammad-postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: zammad_production
            - name: POSTGRES_PASSWORD
              value: zammad
            - name: POSTGRES_USER
              value: zammad
          image: postgres:17.5-alpine
          name: zammad-postgresql
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
      restartPolicy: Always
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data
