apiVersion: apps/v1
kind: Deployment
metadata:
  name: zammad-railsserver
  labels:
    app: zammad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zammad
      component: railsserver
  template:
    metadata:
      labels:
        app: zammad
        component: railsserver
    spec:
      containers:
        - name: railsserver
          image: ghcr.io/zammad/zammad:6.5.0-75
          ports:
            - containerPort: 3000
          env:
            - name: MEMCACHE_SERVERS
              value: "zammad-memcached:11211"
            - name: POSTGRESQL_DB
              value: "zammad_production"
            - name: POSTGRESQL_HOST
              value: "zammad-postgresql"
            - name: POSTGRESQL_USER
              value: "zammad"
            - name: POSTGRESQL_PASS
              value: "zammad"
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: REDIS_URL
              value: "redis://zammad-redis:6379"
            - name: ELASTICSEARCH_HOST
              value: "zammad-elasticsearch"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: TZ
              value: "Europe/Berlin"
            - name: NGINX_PORT
              value: "8080"
          volumeMounts:
            - name: zammad-storage
              mountPath: /opt/zammad/storage
      volumes:
        - name: zammad-storage
          persistentVolumeClaim:
            claimName: zammad-storage-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: zammad-railsserver
spec:
  selector:
    app: zammad
    component: railsserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zammad-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
