apiVersion: v1
kind: Service
metadata:
  name: zammad-redis
  namespace: zammad
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    io.kompose.service: zammad-redis
