apiVersion: v1
kind: Service
metadata:
  name: zammad-elasticsearch
  namespace: zammad
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: elasticsearch
  selector:
    io.kompose.service: zammad-elasticsearch
