apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zammad-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Change la taille en fonction de tes besoins
  storageClassName: standard  # Cela peut varier selon ton fournisseur de cloud
