# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes/
#     kompose.version: 1.36.0 (ae2a39403)
#   labels:
#     io.kompose.service: zammad-nginx
#   name: zammad-nginx
# spec:
#   ports:
#     - name: "8081"
#       port: 8080
#       targetPort: 8080
#   selector:
#     io.kompose.service: zammad-nginx
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: zammad-nginx
  name: zammad-nginx
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 9080
      protocol: TCP
      nodePort: 32543
      name: nginx
  selector:
    io.kompose.service: zammad-nginx
