apiVersion: v1
kind: Service
metadata:
  name: zammad-memcached
  namespace: zammad
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
      name: memcached
  selector:
    io.kompose.service: zammad-memcached
