apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: zammad-redis
  name: zammad-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zammad-redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: zammad-redis
    spec:
      containers:
        - image: redis:7.4.3-alpine
          name: zammad-redis
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
