apiVersion: v1
kind: ConfigMap
metadata:
  name: zammad-config
data:
  MEMCACHE_SERVERS: "zammad-memcached:11211"
  POSTGRESQL_DB: "zammad_production"
  POSTGRESQL_HOST: "zammad-postgresql"
  POSTGRESQL_USER: "zammad"
  POSTGRESQL_PASS: "zammad"
  POSTGRESQL_PORT: "5432"
  REDIS_URL: "redis://zammad-redis:6379"
  ELASTICSEARCH_HOST: "zammad-elasticsearch"
  ELASTICSEARCH_PORT: "9200"
  TZ: "Europe/Berlin"
  NGINX_PORT: "8080"
