apiVersion: v1
kind: Service
metadata:
  name: zammad-railsserver
  namespace: zammad
spec:
  selector:
    app: zammad-railsserver
  ports:
  - protocol: TCP
    port: 3001        # The port that nginx expects to connect to
    targetPort: 3001  # The port the pod listens on
